// <auto-generated />
namespace SGCFT.Seguranca.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Identity_01_CriacaoInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Identity_01_CriacaoInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201910201419577_Identity_01_CriacaoInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
