// <auto-generated />
namespace SGCFT.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _01_Treinamento_Modulo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_01_Treinamento_Modulo));
        
        string IMigrationMetadata.Id
        {
            get { return "201908270337281_01_Treinamento_Modulo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
