// <auto-generated />
namespace SGCFT.Dados.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _05_Ajuste_Entidades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05_Ajuste_Entidades));
        
        string IMigrationMetadata.Id
        {
            get { return "201910121344437_05_Ajuste_Entidades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
